#ifndef CEREAL_REGISTRATION_H
#define CEREAL_REGISTRATION_H

#include <cereal/types/polymorphic.hpp>
#include "Component.h"
#include "SubCircuit.h"

CEREAL_REGISTER_TYPE(Resistor)
CEREAL_REGISTER_TYPE(Capacitor)
CEREAL_REGISTER_TYPE(Inductor)
CEREAL_REGISTER_TYPE(CurrentSource)
CEREAL_REGISTER_TYPE(VoltageSource)
CEREAL_REGISTER_TYPE(ACVoltageSource)
CEREAL_REGISTER_TYPE(SinusoidalVoltageSource)
CEREAL_REGISTER_TYPE(PulseVoltageSource)
CEREAL_REGISTER_TYPE(Diode)
CEREAL_REGISTER_TYPE(VCVS)
CEREAL_REGISTER_TYPE(VCCS)
CEREAL_REGISTER_TYPE(CCVS)
CEREAL_REGISTER_TYPE(CCCS)
CEREAL_REGISTER_TYPE(Ground)

CEREAL_REGISTER_TYPE(SubCircuit)

CEREAL_REGISTER_POLYMORPHIC_RELATION(Component, Resistor)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Component, Capacitor)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Component, Inductor)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Component, CurrentSource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Component, VoltageSource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Component, Diode)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Component, VCVS)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Component, VCCS)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Component, CCVS)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Component, CCCS)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Component, Ground)

CEREAL_REGISTER_POLYMORPHIC_RELATION(Component, SubCircuit)

CEREAL_REGISTER_POLYMORPHIC_RELATION(VoltageSource, ACVoltageSource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(VoltageSource, SinusoidalVoltageSource)
CEREAL_REGISTER_POLYMORPHIC_RELATION(VoltageSource, PulseVoltageSource)


#endif
